---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb-node02
    role: mongoshard
    tier: backend
  name: mongodb-node02
spec:
  ports:
    -
      name: arb04-node02
      port: 27019
      protocol: TCP
    -
      name: cfg02-node02
      port: 27018
      protocol: TCP
    -
      name: mgs02-node02
      port: 27017
      protocol: TCP
    -
      name: rsp02-node02
      port: 27020
      protocol: TCP
    -
      name: rss01-node02
      port: 27021
      protocol: TCP
  selector:
    app: mongodb-shard-node02
    role: mongoshard
    tier: backend
