---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb-node01
    role: mongoshard
    tier: backend
  name: mongodb-node01
spec:
  ports:
    -
      name: arb03-node01
      port: 27019
      protocol: TCP
    -
      name: cfg01-node01
      port: 27018
      protocol: TCP
    -
      name: mgs01-node01
      port: 27017
      protocol: TCP
    -
      name: rsp01-node01
      port: 27020
      protocol: TCP
    -
      name: rss04-node01
      port: 27021
      protocol: TCP
  selector:
    app: mongodb-shard-node01
    role: mongoshard
    tier: backend
