kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: mysql-pvc
   annotations:
     volume.beta.kubernetes.io/storage-class: mysql-ha-sc
spec:
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 10Gi
