# pod.yaml
kind: Pod
apiVersion: v1
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
    - name: mysql
      image: mysql:8.0
      imagePullPolicy: Always
      ports:
        - containerPort: 3306
          name: mysql
      env:
      - name: MYSQL_ROOT_PASSWORD # use only for debugging
        value: "TeamFirst=1!"
      - name: MYSQL_DATABASE
        value: "aruba_academy"
      - name: MYSQL_USER
        value: "k8s"
      - name: MYSQL_PASSWORD
        value: "TeamFirst=1!"
      volumeMounts:
      - name: mysql-ha-sc  ## specify volume name
        mountPath: /etc/mysql/conf.d/default_auth.cnf ## path to mount file
        subPath: default_auth ## name of config
  volumes:   
    - name: mysql-ha-sc ## volume name
      persistentVolumeClaim:
        claimName: mysql-pvc
